# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d739393f474861e30e69543ff076b2313a48a84715d643f8df14e3bea138d9866cc28ca2c7793dd037e6b8a0441f02f4514c756665637f0030698314960dadc8

test:
  secret_key_base: 650f9075abc55e135043edab2aa230bfb3471047cde22f55dc05f1b2c477ba8f50ff351c2b873669df8804d066efccaf8df65fc478661633e6637e84969a9852

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
